---
title: What file formats are on the data portals?
---
```{r configure, echo = F}
opts_chunk$set(fig.width=10, fig.height=5, dpi = 42 * 5)
```

While [at Socrata's office]() on Friday,
I learned of the [`/data.json`](https://data.oregon.gov/data.json) endpoint.
It contains an entry for each [dataset](),
uploaded by the data publisher; it doesn't contain all of the other
views that are based on these source datasets.
And it has [this format](http://project-open-data.github.io/schema/).

Socrata portals have [50,000 different views](), but only
`r nrow(datasets)` are.

```{r portal-counts, fig.width = 10, fig.height = 15}
p.portal.counts
```

CSV

```{r csv-cum-facet, fig.width = 20, fig.height = 10}
p.csv.cum.facet
```


Some interesting portals

```{r mo}
p.data.mo.gov
```

```{r csv-pdf-cum-facet, fig.width = 20, fig.height = 10}
p.csv.pdf.cum.facet
```

```{r hawaii}
p.data.hawaii.gov
```

```{r lehman}
p.bronx.lehman.cuny.edu
```

```{r all-formats, fig.width = 10, fig.height = 15}
p.all
```

```{r sf}
p.data.sfgov.org
```
